name: 'Summarize all files in a repo'
author: 'xander-rudolph'
branding:
  icon: 'anchor'
  color: 'green'
description: 'Reads the whole repository to generate a readme.md file'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: ${{ github.workspace }}
  output_format:
    description: "Type of output file to return"
    required: false
    default: md

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      
    - name: Run Python script
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ inputs.working_dir }}
        OUTPUT_FORMAT: ${{ inputs.output_format }}
      run: python ${{ github.action_path }}/script.py

    - name: Add to summary
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ inputs.working_dir }}
      run: |
        cat "$GITHUB_WORKSPACE/readme.md" >> $GITHUB_STEP_SUMMARY
