vname: 'Run Trivy scan - linux - with summary'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any vulnerabilities and adds a step summary'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: ${{ github.workspace }}
  output_format:
    description: "Type of output file to return"
    required: false
    default: md

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install ${{ github.action_path }}/requirements.txt
      
    - name: Run Python script
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: python ${{ github.action_path }}/script.py
